/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RrhhRouteImport } from './routes/rrhh'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as RecaudacionesRouteImport } from './routes/recaudaciones'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PagosRouteImport } from './routes/pagos'
import { Route as FiscalizacionRouteImport } from './routes/fiscalizacion'
import { Route as ExpedientesRouteImport } from './routes/expedientes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CatastroRouteImport } from './routes/catastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RrhhSolicitudesRouteImport } from './routes/rrhh.solicitudes'
import { Route as RrhhPlanillasRouteImport } from './routes/rrhh.planillas'
import { Route as RrhhOrganigramaRouteImport } from './routes/rrhh.organigrama'
import { Route as RrhhFuncionariosRouteImport } from './routes/rrhh.funcionarios'
import { Route as RecaudacionesMoraRouteImport } from './routes/recaudaciones.mora'
import { Route as RecaudacionesDeudasRouteImport } from './routes/recaudaciones.deudas'
import { Route as RecaudacionesContribuyentesRouteImport } from './routes/recaudaciones.contribuyentes'
import { Route as RecaudacionesConceptosRouteImport } from './routes/recaudaciones.conceptos'
import { Route as CatastroZonasRouteImport } from './routes/catastro.zonas'
import { Route as CatastroTramitesRouteImport } from './routes/catastro.tramites'
import { Route as CatastroPrediosRouteImport } from './routes/catastro.predios'
import { Route as CatastroMapaRouteImport } from './routes/catastro.mapa'

const RrhhRoute = RrhhRouteImport.update({
  id: '/rrhh',
  path: '/rrhh',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecaudacionesRoute = RecaudacionesRouteImport.update({
  id: '/recaudaciones',
  path: '/recaudaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosRoute = PagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const FiscalizacionRoute = FiscalizacionRouteImport.update({
  id: '/fiscalizacion',
  path: '/fiscalizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpedientesRoute = ExpedientesRouteImport.update({
  id: '/expedientes',
  path: '/expedientes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CatastroRoute = CatastroRouteImport.update({
  id: '/catastro',
  path: '/catastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RrhhSolicitudesRoute = RrhhSolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => RrhhRoute,
} as any)
const RrhhPlanillasRoute = RrhhPlanillasRouteImport.update({
  id: '/planillas',
  path: '/planillas',
  getParentRoute: () => RrhhRoute,
} as any)
const RrhhOrganigramaRoute = RrhhOrganigramaRouteImport.update({
  id: '/organigrama',
  path: '/organigrama',
  getParentRoute: () => RrhhRoute,
} as any)
const RrhhFuncionariosRoute = RrhhFuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => RrhhRoute,
} as any)
const RecaudacionesMoraRoute = RecaudacionesMoraRouteImport.update({
  id: '/mora',
  path: '/mora',
  getParentRoute: () => RecaudacionesRoute,
} as any)
const RecaudacionesDeudasRoute = RecaudacionesDeudasRouteImport.update({
  id: '/deudas',
  path: '/deudas',
  getParentRoute: () => RecaudacionesRoute,
} as any)
const RecaudacionesContribuyentesRoute =
  RecaudacionesContribuyentesRouteImport.update({
    id: '/contribuyentes',
    path: '/contribuyentes',
    getParentRoute: () => RecaudacionesRoute,
  } as any)
const RecaudacionesConceptosRoute = RecaudacionesConceptosRouteImport.update({
  id: '/conceptos',
  path: '/conceptos',
  getParentRoute: () => RecaudacionesRoute,
} as any)
const CatastroZonasRoute = CatastroZonasRouteImport.update({
  id: '/zonas',
  path: '/zonas',
  getParentRoute: () => CatastroRoute,
} as any)
const CatastroTramitesRoute = CatastroTramitesRouteImport.update({
  id: '/tramites',
  path: '/tramites',
  getParentRoute: () => CatastroRoute,
} as any)
const CatastroPrediosRoute = CatastroPrediosRouteImport.update({
  id: '/predios',
  path: '/predios',
  getParentRoute: () => CatastroRoute,
} as any)
const CatastroMapaRoute = CatastroMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => CatastroRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catastro': typeof CatastroRouteWithChildren
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/expedientes': typeof ExpedientesRoute
  '/fiscalizacion': typeof FiscalizacionRoute
  '/pagos': typeof PagosRoute
  '/portal': typeof PortalRoute
  '/recaudaciones': typeof RecaudacionesRouteWithChildren
  '/reportes': typeof ReportesRoute
  '/rrhh': typeof RrhhRouteWithChildren
  '/catastro/mapa': typeof CatastroMapaRoute
  '/catastro/predios': typeof CatastroPrediosRoute
  '/catastro/tramites': typeof CatastroTramitesRoute
  '/catastro/zonas': typeof CatastroZonasRoute
  '/recaudaciones/conceptos': typeof RecaudacionesConceptosRoute
  '/recaudaciones/contribuyentes': typeof RecaudacionesContribuyentesRoute
  '/recaudaciones/deudas': typeof RecaudacionesDeudasRoute
  '/recaudaciones/mora': typeof RecaudacionesMoraRoute
  '/rrhh/funcionarios': typeof RrhhFuncionariosRoute
  '/rrhh/organigrama': typeof RrhhOrganigramaRoute
  '/rrhh/planillas': typeof RrhhPlanillasRoute
  '/rrhh/solicitudes': typeof RrhhSolicitudesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catastro': typeof CatastroRouteWithChildren
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/expedientes': typeof ExpedientesRoute
  '/fiscalizacion': typeof FiscalizacionRoute
  '/pagos': typeof PagosRoute
  '/portal': typeof PortalRoute
  '/recaudaciones': typeof RecaudacionesRouteWithChildren
  '/reportes': typeof ReportesRoute
  '/rrhh': typeof RrhhRouteWithChildren
  '/catastro/mapa': typeof CatastroMapaRoute
  '/catastro/predios': typeof CatastroPrediosRoute
  '/catastro/tramites': typeof CatastroTramitesRoute
  '/catastro/zonas': typeof CatastroZonasRoute
  '/recaudaciones/conceptos': typeof RecaudacionesConceptosRoute
  '/recaudaciones/contribuyentes': typeof RecaudacionesContribuyentesRoute
  '/recaudaciones/deudas': typeof RecaudacionesDeudasRoute
  '/recaudaciones/mora': typeof RecaudacionesMoraRoute
  '/rrhh/funcionarios': typeof RrhhFuncionariosRoute
  '/rrhh/organigrama': typeof RrhhOrganigramaRoute
  '/rrhh/planillas': typeof RrhhPlanillasRoute
  '/rrhh/solicitudes': typeof RrhhSolicitudesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catastro': typeof CatastroRouteWithChildren
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/expedientes': typeof ExpedientesRoute
  '/fiscalizacion': typeof FiscalizacionRoute
  '/pagos': typeof PagosRoute
  '/portal': typeof PortalRoute
  '/recaudaciones': typeof RecaudacionesRouteWithChildren
  '/reportes': typeof ReportesRoute
  '/rrhh': typeof RrhhRouteWithChildren
  '/catastro/mapa': typeof CatastroMapaRoute
  '/catastro/predios': typeof CatastroPrediosRoute
  '/catastro/tramites': typeof CatastroTramitesRoute
  '/catastro/zonas': typeof CatastroZonasRoute
  '/recaudaciones/conceptos': typeof RecaudacionesConceptosRoute
  '/recaudaciones/contribuyentes': typeof RecaudacionesContribuyentesRoute
  '/recaudaciones/deudas': typeof RecaudacionesDeudasRoute
  '/recaudaciones/mora': typeof RecaudacionesMoraRoute
  '/rrhh/funcionarios': typeof RrhhFuncionariosRoute
  '/rrhh/organigrama': typeof RrhhOrganigramaRoute
  '/rrhh/planillas': typeof RrhhPlanillasRoute
  '/rrhh/solicitudes': typeof RrhhSolicitudesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catastro'
    | '/configuracion'
    | '/dashboard'
    | '/expedientes'
    | '/fiscalizacion'
    | '/pagos'
    | '/portal'
    | '/recaudaciones'
    | '/reportes'
    | '/rrhh'
    | '/catastro/mapa'
    | '/catastro/predios'
    | '/catastro/tramites'
    | '/catastro/zonas'
    | '/recaudaciones/conceptos'
    | '/recaudaciones/contribuyentes'
    | '/recaudaciones/deudas'
    | '/recaudaciones/mora'
    | '/rrhh/funcionarios'
    | '/rrhh/organigrama'
    | '/rrhh/planillas'
    | '/rrhh/solicitudes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catastro'
    | '/configuracion'
    | '/dashboard'
    | '/expedientes'
    | '/fiscalizacion'
    | '/pagos'
    | '/portal'
    | '/recaudaciones'
    | '/reportes'
    | '/rrhh'
    | '/catastro/mapa'
    | '/catastro/predios'
    | '/catastro/tramites'
    | '/catastro/zonas'
    | '/recaudaciones/conceptos'
    | '/recaudaciones/contribuyentes'
    | '/recaudaciones/deudas'
    | '/recaudaciones/mora'
    | '/rrhh/funcionarios'
    | '/rrhh/organigrama'
    | '/rrhh/planillas'
    | '/rrhh/solicitudes'
  id:
    | '__root__'
    | '/'
    | '/catastro'
    | '/configuracion'
    | '/dashboard'
    | '/expedientes'
    | '/fiscalizacion'
    | '/pagos'
    | '/portal'
    | '/recaudaciones'
    | '/reportes'
    | '/rrhh'
    | '/catastro/mapa'
    | '/catastro/predios'
    | '/catastro/tramites'
    | '/catastro/zonas'
    | '/recaudaciones/conceptos'
    | '/recaudaciones/contribuyentes'
    | '/recaudaciones/deudas'
    | '/recaudaciones/mora'
    | '/rrhh/funcionarios'
    | '/rrhh/organigrama'
    | '/rrhh/planillas'
    | '/rrhh/solicitudes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatastroRoute: typeof CatastroRouteWithChildren
  ConfiguracionRoute: typeof ConfiguracionRoute
  DashboardRoute: typeof DashboardRoute
  ExpedientesRoute: typeof ExpedientesRoute
  FiscalizacionRoute: typeof FiscalizacionRoute
  PagosRoute: typeof PagosRoute
  PortalRoute: typeof PortalRoute
  RecaudacionesRoute: typeof RecaudacionesRouteWithChildren
  ReportesRoute: typeof ReportesRoute
  RrhhRoute: typeof RrhhRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rrhh': {
      id: '/rrhh'
      path: '/rrhh'
      fullPath: '/rrhh'
      preLoaderRoute: typeof RrhhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recaudaciones': {
      id: '/recaudaciones'
      path: '/recaudaciones'
      fullPath: '/recaudaciones'
      preLoaderRoute: typeof RecaudacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos': {
      id: '/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof PagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiscalizacion': {
      id: '/fiscalizacion'
      path: '/fiscalizacion'
      fullPath: '/fiscalizacion'
      preLoaderRoute: typeof FiscalizacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expedientes': {
      id: '/expedientes'
      path: '/expedientes'
      fullPath: '/expedientes'
      preLoaderRoute: typeof ExpedientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catastro': {
      id: '/catastro'
      path: '/catastro'
      fullPath: '/catastro'
      preLoaderRoute: typeof CatastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rrhh/solicitudes': {
      id: '/rrhh/solicitudes'
      path: '/solicitudes'
      fullPath: '/rrhh/solicitudes'
      preLoaderRoute: typeof RrhhSolicitudesRouteImport
      parentRoute: typeof RrhhRoute
    }
    '/rrhh/planillas': {
      id: '/rrhh/planillas'
      path: '/planillas'
      fullPath: '/rrhh/planillas'
      preLoaderRoute: typeof RrhhPlanillasRouteImport
      parentRoute: typeof RrhhRoute
    }
    '/rrhh/organigrama': {
      id: '/rrhh/organigrama'
      path: '/organigrama'
      fullPath: '/rrhh/organigrama'
      preLoaderRoute: typeof RrhhOrganigramaRouteImport
      parentRoute: typeof RrhhRoute
    }
    '/rrhh/funcionarios': {
      id: '/rrhh/funcionarios'
      path: '/funcionarios'
      fullPath: '/rrhh/funcionarios'
      preLoaderRoute: typeof RrhhFuncionariosRouteImport
      parentRoute: typeof RrhhRoute
    }
    '/recaudaciones/mora': {
      id: '/recaudaciones/mora'
      path: '/mora'
      fullPath: '/recaudaciones/mora'
      preLoaderRoute: typeof RecaudacionesMoraRouteImport
      parentRoute: typeof RecaudacionesRoute
    }
    '/recaudaciones/deudas': {
      id: '/recaudaciones/deudas'
      path: '/deudas'
      fullPath: '/recaudaciones/deudas'
      preLoaderRoute: typeof RecaudacionesDeudasRouteImport
      parentRoute: typeof RecaudacionesRoute
    }
    '/recaudaciones/contribuyentes': {
      id: '/recaudaciones/contribuyentes'
      path: '/contribuyentes'
      fullPath: '/recaudaciones/contribuyentes'
      preLoaderRoute: typeof RecaudacionesContribuyentesRouteImport
      parentRoute: typeof RecaudacionesRoute
    }
    '/recaudaciones/conceptos': {
      id: '/recaudaciones/conceptos'
      path: '/conceptos'
      fullPath: '/recaudaciones/conceptos'
      preLoaderRoute: typeof RecaudacionesConceptosRouteImport
      parentRoute: typeof RecaudacionesRoute
    }
    '/catastro/zonas': {
      id: '/catastro/zonas'
      path: '/zonas'
      fullPath: '/catastro/zonas'
      preLoaderRoute: typeof CatastroZonasRouteImport
      parentRoute: typeof CatastroRoute
    }
    '/catastro/tramites': {
      id: '/catastro/tramites'
      path: '/tramites'
      fullPath: '/catastro/tramites'
      preLoaderRoute: typeof CatastroTramitesRouteImport
      parentRoute: typeof CatastroRoute
    }
    '/catastro/predios': {
      id: '/catastro/predios'
      path: '/predios'
      fullPath: '/catastro/predios'
      preLoaderRoute: typeof CatastroPrediosRouteImport
      parentRoute: typeof CatastroRoute
    }
    '/catastro/mapa': {
      id: '/catastro/mapa'
      path: '/mapa'
      fullPath: '/catastro/mapa'
      preLoaderRoute: typeof CatastroMapaRouteImport
      parentRoute: typeof CatastroRoute
    }
  }
}

interface CatastroRouteChildren {
  CatastroMapaRoute: typeof CatastroMapaRoute
  CatastroPrediosRoute: typeof CatastroPrediosRoute
  CatastroTramitesRoute: typeof CatastroTramitesRoute
  CatastroZonasRoute: typeof CatastroZonasRoute
}

const CatastroRouteChildren: CatastroRouteChildren = {
  CatastroMapaRoute: CatastroMapaRoute,
  CatastroPrediosRoute: CatastroPrediosRoute,
  CatastroTramitesRoute: CatastroTramitesRoute,
  CatastroZonasRoute: CatastroZonasRoute,
}

const CatastroRouteWithChildren = CatastroRoute._addFileChildren(
  CatastroRouteChildren,
)

interface RecaudacionesRouteChildren {
  RecaudacionesConceptosRoute: typeof RecaudacionesConceptosRoute
  RecaudacionesContribuyentesRoute: typeof RecaudacionesContribuyentesRoute
  RecaudacionesDeudasRoute: typeof RecaudacionesDeudasRoute
  RecaudacionesMoraRoute: typeof RecaudacionesMoraRoute
}

const RecaudacionesRouteChildren: RecaudacionesRouteChildren = {
  RecaudacionesConceptosRoute: RecaudacionesConceptosRoute,
  RecaudacionesContribuyentesRoute: RecaudacionesContribuyentesRoute,
  RecaudacionesDeudasRoute: RecaudacionesDeudasRoute,
  RecaudacionesMoraRoute: RecaudacionesMoraRoute,
}

const RecaudacionesRouteWithChildren = RecaudacionesRoute._addFileChildren(
  RecaudacionesRouteChildren,
)

interface RrhhRouteChildren {
  RrhhFuncionariosRoute: typeof RrhhFuncionariosRoute
  RrhhOrganigramaRoute: typeof RrhhOrganigramaRoute
  RrhhPlanillasRoute: typeof RrhhPlanillasRoute
  RrhhSolicitudesRoute: typeof RrhhSolicitudesRoute
}

const RrhhRouteChildren: RrhhRouteChildren = {
  RrhhFuncionariosRoute: RrhhFuncionariosRoute,
  RrhhOrganigramaRoute: RrhhOrganigramaRoute,
  RrhhPlanillasRoute: RrhhPlanillasRoute,
  RrhhSolicitudesRoute: RrhhSolicitudesRoute,
}

const RrhhRouteWithChildren = RrhhRoute._addFileChildren(RrhhRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatastroRoute: CatastroRouteWithChildren,
  ConfiguracionRoute: ConfiguracionRoute,
  DashboardRoute: DashboardRoute,
  ExpedientesRoute: ExpedientesRoute,
  FiscalizacionRoute: FiscalizacionRoute,
  PagosRoute: PagosRoute,
  PortalRoute: PortalRoute,
  RecaudacionesRoute: RecaudacionesRouteWithChildren,
  ReportesRoute: ReportesRoute,
  RrhhRoute: RrhhRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
